In [1]:
import numpy as np

In [2]:
np.sum([1,3])

4

In [3]:
sum([1,3])

4

In [4]:
np.__version__

'1.16.5'

In [ ]:
!conda install -c numpy

In [ ]:
!pip install --upgrade numpy

In [1]:
np.__version__

NameError: name 'np' is not defined

In [3]:
np.sum([1,3])

NameError: name 'np' is not defined

In [ ]:
!pip install --upgrade numpy

In [1]:
np.sum([1,3])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.2'

In [ ]:
# %load code.py
import urllib.request, urllib.parse, urllib.error
import json
import ssl

api_key = False
# If you have a Google Places API key, enter it here
# api_key = 'AIzaSy___IDByT70'
# https://developers.google.com/maps/documentation/geocoding/intro

if api_key is False:
    api_key = 42
    serviceurl = 'http://py4e-data.dr-chuck.net/json?'
else :
    serviceurl = 'https://maps.googleapis.com/maps/api/geocode/json?'

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

while True:
    address = input('Enter location: ')
    if len(address) < 1: break

    parms = dict()
    parms['address'] = address
    if api_key is not False: parms['key'] = api_key
    url = serviceurl + urllib.parse.urlencode(parms)

    print('Retrieving', url)
    uh = urllib.request.urlopen(url, context=ctx)
    data = uh.read().decode()
    print('Retrieved', len(data), 'characters')

    try:
        js = json.loads(data)
    except:
        js = None

    if not js or 'status' not in js or js['status'] != 'OK':
        print('==== Failure To Retrieve ====')
        print(data["results"])
        continue
    print(js["results"])

    

In [10]:
# %load code.py
import urllib.request, urllib.parse, urllib.error
import json
import ssl

api_key = False
# If you have a Google Places API key, enter it here
# api_key = 'AIzaSy___IDByT70'
# https://developers.google.com/maps/documentation/geocoding/intro

if api_key is False:
    api_key = 42
    serviceurl = 'http://py4e-data.dr-chuck.net/json?'
else :
    serviceurl = 'https://maps.googleapis.com/maps/api/geocode/json?'

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

while True:
    address = input('Enter location: ')
    if len(address) < 1: break

    parms = dict()
    parms['address'] = address
    if api_key is not False: parms['key'] = api_key
    url = serviceurl + urllib.parse.urlencode(parms)

    print('Retrieving', url)
    uh = urllib.request.urlopen(url, context=ctx)
    data = uh.read().decode()
    print('Retrieved', len(data), 'characters')

    try:
        js = json.loads(data)
    except:
        js = None

    if not js or 'status' not in js or js['status'] != 'OK':
        print('==== Failure To Retrieve ====')
        print(data["results"])
        continue
    print(js["results"])

%time

Enter location: http://py4e-data.dr-chuck.net/json?address=http%3A%5C%5Cgoogle.com&key=42
Retrieving http://py4e-data.dr-chuck.net/json?address=http%3A%2F%2Fpy4e-data.dr-chuck.net%2Fjson%3Faddress%3Dhttp%253A%255C%255Cgoogle.com%26key%3D42&key=42
Retrieved 52 characters
==== Failure To Retrieve ====


TypeError: string indices must be integers

In [7]:
%time np.arange(1,1000000)

Wall time: 2 ms


array([     1,      2,      3, ..., 999997, 999998, 999999])

In [11]:
l = np.arange(1,1000000)
l = l +5
l

array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [12]:
l.shape

(999999,)

In [13]:
l.ndim

1

In [16]:
a=np.array([1])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1]
1
(1,)
int32


In [17]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1 2 3 4]
1
(4,)
int32


In [19]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [21]:
a = np.arange(1,10).reshape((3,3))
a = a+5
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
a = np.arange(1,31).reshape(3,5,2)
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [30]:
a = np.random.randn(2,3)
print(a)

[[-0.03710451  1.85224479 -0.13562099]
 [ 0.10358691  0.47048288  0.01429845]]


In [ ]:
a = np.random.randint()